- README.md
Added environment variables needed for OAuth2 authentication and service proxying.
> RDM-1353: OAuth2 documentation update

- app.js
- app/app-insights/app-insights.js
- test/user/user-request-authorizer.spec.js
Added applicationInsight integration to the top of everything as recommended
Added a parameter to error handler function fix for issue spotted by @Daniel-Lam 
Fixed several lint complaints
Jira task# RDM-1742
> RDM-1742 fixed linting errors, appInsight initialized correctly

- app/app-insights/app-insights.js
- test/app-insights/app-insights.spec.js
RDM-1742 Sonar Improvements
- added a test scenario 
- removed logging about initialization
> Rdm 1742 - Sonar Report Fixes

- Jenkinsfile_CNP
- app.js
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/variables.tf
N/A
Add `/` as alias to `/health` to support Azure's keep-alive.
Use `product` and `component` from Jenkinsfile
```
[ ] Yes
[x] No
```
> Fixes for CNP pipelines

- infrastructure/main.tf
N/A
Fix syntax error in `main.tf`
```
[ ] Yes
[x] No
```
> Fix TF syntax error

- app/oauth2/access-token-request.js
N/A
Dynamically add `https://` to redirect URI
```
[ ] Yes
[x] No
```
> Dynamically add `https://` to redirect URI

- test/oauth2/access-token-request.spec.js
N/A
Test https:// prefixing, fix failing quality gate
```
[ ] Yes
[ ] No
```
> Test https:// prefixing

- infrastructure/main.tf
N/A
Make `is_frontend` true only when external host name provided
Replace default additional hostname by null
```
[ ] Yes
[x] No
```
> Fix multiple DNS error for Sandbox

- infrastructure/main.tf
N/A
Give booleans as integers
```
[ ] Yes
[x] No
```
> Give booleans as integers

- infrastructure/main.tf
N/A
Use HTTP for internal urls.
```
[ ] Yes
[x] No
```
> Switch sandbox print service to http

- hub.Dockerfile
RDM-2050
I created a hub.Dockerfile to test docker image creation.  If it worked, then the next step is to delete Dockerfile
```
[x] Yes
[ ] No
```
> Attempt to create a docker image

- .dockerignore
- Dockerfile
- docker-compose.yml
> Add docker images

- Jenkinsfile_parameterized
Only deploy to saat or sprod, nayab was accidentally deploying to sandbox before
```
[ ] Yes
[ ] No
```
> Remove unneeded options

- infrastructure/aat.tfvars
- infrastructure/main.tf
N/A
Allow * for preview cors_origin
```
[x] Yes
[ ] No
```
> Allow * for preview cors_origin

- infrastructure/aat.tfvars
Reverts hmcts/ccd-api-gateway#35
> Revert "Allow * for preview cors_origin"

- infrastructure/preview.tfvars
> Adding for preview

- app/security/cors.js
- test/security/cors.spec.js
N/A
Fix to allow use of wilcard for CORS in preview environment
```
[ ] Yes
[x] No
```
> Fix support for CORS origin wildcard

- infrastructure/aat.tfvars
N/A
Correct AAT to use `nonprod` external hostname
```
[ ] Yes
[x] No
```
> [SKIP-PREVIEW] Correct AAT external hostname

- config/default.yaml
N/A
Use secrets defined by `ccd-docker` to run locally
```
[ ] Yes
[x] No
```
> [SKIP-PREVIEW] Set default secrets

- .travis.yml
- README.md
- package.json
> Amend Travis as per https://github.com/codecov/example-node

- README.md
N/A
Enable Greenkeeper
```
[ ] Yes
[x] No
```
> Enable Greenkeeper

- Jenkinsfile_nightly
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-2311
> Add basic Jenkins nightly builds

- Jenkinsfile_parameterized
Updated the pipeline so we can get an option to deploy to sandbox
```
[ ] Yes
[ x] No
```
> add_deploy_to_sandbox

- config/default.yaml
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2223
- Added PUT to the allowed methods to let updating the draft data.
- Also added service key for local docker integration
```
[ ] Yes
[X] No
```
> RDM-2223 Allow PUT method in api-gateway

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2484
```
[ ] Yes
[x] No
```
> [PREVIEW] Remove Hashi vault

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2635
```
[ ] Yes
[x] No
```
> [PREVIEW] Infra: use specific shared ASP resource group

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-3154
```
[ ] Yes
[x] No
```
> Add cross-env as a prod dependency

- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-2789
```
[ ] Yes
[ ] No
```
> Sync yarn.lock to package.json

- infrastructure/main.tf
N/A
Whitelist to allow smoke tests to run against prod staging slot
```
[ ] Yes
[x] No
```
> Whitelist CORS staging slot for tests

- infrastructure/main.tf
- infrastructure/outputs.tf
RDM-2931
https://tools.hmcts.net/jira/browse/RDM-2931
```
[ ] Yes
[ ] No
```
> [PREVIEW] Use s2s vault fr microservice keys

- infrastructure/sprod.tfvars
RDM-3570
Configure SProd with a proper hostname to replicate Prod setup.
```
[ ] Yes
[x] No
```
> RDM-3570: Set SProd hostname

- .travis.yml
- Jenkinsfile_CNP
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-2742
```
[ ] Yes
[ ] No
```
> Cleanup yarn check errors

- infrastructure/demo.tfvars
N/A
Update Demo environment to use AppGW-compatible domain
```
[ ] Yes
[x] No
```
> Use `-ccd.demo` domain

- Jenkinsfile_CNP
- charts/ccd-api-gateway-web/Chart.yaml
- charts/ccd-api-gateway-web/requirements.yaml
- charts/ccd-api-gateway-web/values.aat.template.yaml
- charts/ccd-api-gateway-web/values.template.yaml
https://tools.hmcts.net/jira/browse/RDM-3224
```
[ ] Yes
[ ] No
```
> Enable Helm Charts

- .travis.yml
- Dockerfile
- package.json
https://tools.hmcts.net/jira/browse/RDM-3320
```
[ ] Yes
[ ] No
```
> Set minimum yarn version

- infrastructure/aat.tfvars
https://tools.hmcts.net/jira/browse/RDM-3860
Use update DNS for ccd-api-gateway in AAT: https://gateway-ccd.aat.platform.hmcts.net
```
[ ] Yes
[x] No
```
> update new gw url

- charts/ccd-api-gateway-web/Chart.yaml
- charts/ccd-api-gateway-web/requirements.yaml
- charts/ccd-api-gateway-web/values.aat.template.yaml
- charts/ccd-api-gateway-web/values.template.yaml
> Cleanup: chart names

- yarn.lock
> Bump extend to v3.0.2

- hub.Dockerfile
https://tools.hmcts.net/jira/browse/RDM-4058
```
[ ] Yes
[ ] No
```
> Add Dockerfile for Docker hub

- Jenkinsfile_CNP
- app/address/address-lookup.js
- app/oauth2/access-token-request.js
- app/oauth2/logout-route.js
- app/service/service-token-generator.js
- charts/ccd-api-gateway-web/Chart.yaml
- charts/ccd-api-gateway-web/requirements.yaml
- charts/ccd-api-gateway-web/values.template.yaml
- config/custom-environment-variables.yaml
- config/default.yaml
- package.json
- server.js
- test/oauth2/access-token-request.spec.js
- test/oauth2/logout-route.spec.js
- test/service/service-token-generator.spec.js
- yarn.lock
Adding secrets as flex volumes 
Upgrading NodeJs Chart
https://tools.hmcts.net/jira/browse/RPE-1005
Adding secrets as flex volumes 
Upgrading NodeJs Chart
```
[ ] Yes
[x] No
```
> Adding secrets as flex volumes

- charts/ccd-api-gateway-web/values.template.yaml
Removing releasename override to pick default
https://tools.hmcts.net/jira/browse/RPE-1009
Removing releasename override to pick default
```
[ ] Yes
[x] No
```
> Removing releasename override to pick default

- infrastructure/preview.tfvars
changed aat.tfvars to look at SIDAM instead of TIDAM
> Switch AAT to SIDAM #417

- infrastructure/saat.tfvars
> Sidam switch

- infrastructure/perftest.tfvars
https://tools.hmcts.net/jira/browse/RDM-4571
```
[ ] Yes
[ ] No
```
> Use formal idam-api URL

- app.js
Payments web-component has been updated to support telephony payments. The view the payments now the new end-points will be accessed.
```
[ ] Yes
[ ] No
```
> Payhub new end-point updated

- app.js
Added context path /payment to the payment-group end-point
```
[ ] Yes
[ ] No
```
> Added context path /payment to the end-point

- infrastructure/main.tf
> push dummy var to force tf change

- Dockerfile
- acb.tpl.yaml
- docker-compose.yml
> RDM-5330-update ccd to use new docker registry url

- app.js
https://tools.hmcts.net/jira/browse/PAY-1732
Payments List for Telephony MVP
```
[ ] Yes
[X] No
```
> PAY-1732 -> Telephony MVP

- charts/ccd-api-gateway-web/Chart.yaml
- charts/ccd-api-gateway-web/requirements.yaml
> bump up base chart version

- yarn-audit-known-issues
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDM-5586
Change description
Media viewer - Updated to include the annotations API
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> temporarily ignore to get MV with annots deployed on demo for testing

- yarn-audit-known-issues
https://tools.hmcts.net/jira/browse/RDM-5586
Media viewer - Updated to include the annotations API
```
[ ] Yes
[x] No
```
> add npmjs url

- package.json
- yarn-audit-known-issues
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-5963
https://tools.hmcts.net/jira/browse/RDM-5964
Bumped vulnerable dependencies versions. Removed related suppressions.
```
[ ] Yes
[X ] No
```
> RDM-5963 RDM-5964 vulnerabilities fix

- infrastructure/ithc.tfvars
Expose annotations api from CCD gw.
```
[ ] Yes
[X] No
```
> add ithc downstream url for annotations api

- infrastructure/ithc.tfvars
> Rdm 5582 upgrade mv version for annotations

- charts/ccd-api-gateway-web/Chart.yaml
- package.json
- yarn.lock
Updated Chart Attributes to work with latest HELM
```
[ ] Yes
[ x] No
```
> RDM-6674-updated chart, compatible with laetst HELM and CVE fixes

- app.js
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-5535
Add nocache middleware to ensure every API response is not cached.
```
[ ] Yes
[x] No
```
> RDM-5535 Add nocache middleware

- charts/ccd-api-gateway-web/values.aat.template.yaml
- charts/ccd-api-gateway-web/values.preview.template.yaml
- charts/ccd-api-gateway-web/values.yaml
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/ithc.tfvars
- infrastructure/main.tf
- infrastructure/preview.tfvars
https://tools.hmcts.net/jira/browse/RDM-5806
Update CORS whitelists
```
[ ] Yes
[x] No
```
> RDM-5806 Update CORS whitelists

- app.js
- charts/ccd-api-gateway-web/values.yaml
- config/custom-environment-variables.yaml
- config/default.yaml
- infrastructure/main.tf
Reverts hmcts/ccd-api-gateway#266
> Revert " RDM-6635 pay bulkscan integration"

- charts/ccd-api-gateway-web/values.yaml
https://tools.hmcts.net/jira/browse/RDM-7056
Fix ITHC Login Failure by parameterising external URL
```
[ ] Yes
[X] No
```
> RDM-7056 - ITHC Login Failure

- web.config
https://tools.hmcts.net/jira/browse/RDM-6999
Increse file upload size limit from 100 to 500 MB.
```
[ ] Yes
[x] No
```
> RDM-6999 : Increse file upload size limit from 100 to 500 MB.

- infrastructure/ithc.tfvars
https://tools.hmcts.net/jira/browse/RDM-7264
remove space in cors allowed list
```
[ ] Yes
[X] No
```
> remove space in cors allowed list

- app.js
- charts/ccd-api-gateway-web/values.yaml
- config/custom-environment-variables.yaml
- config/default.yaml
- infrastructure/main.tf
Reverts hmcts/ccd-api-gateway#276
> RDM-6635 pay bulkscan integration

- web.config
https://tools.hmcts.net/jira/browse/RDM-6926
Enable Upload and Download of Large Multimedia Files
```
[ ] Yes
[x] No
```
> RDM-6926 : Increase file upload size limit from 100 to 500 MB

- infrastructure/ithc.tfvars
> RDM-7695 Update-IDAM-URLs

- package.json
> Draft nodeJS - >=12.13.0

- package.json
https://build.platform.hmcts.net/job/HMCTS_CDM/job/ccd-api-gateway/job/master/44/console
```
[ ] Yes
[x] No
```
> Fix NodeJS version to match AZ runtime

- charts/ccd-api-gateway-web/Chart.yaml
- charts/ccd-api-gateway-web/values.preview.template.yaml
- charts/ccd-api-gateway-web/values.yaml
- package.json
- yarn.lock
Print service goes externally from case-management web but internally from the gateway.
Seems absolutely pointless to have a proxy for something that is publicly accessible but I didn't want to change that or have the gateway traverse another 8 networks hops to go public again
> Point api-gateway to go to service for print service

- charts/ccd-api-gateway-web/Chart.yaml
- charts/ccd-api-gateway-web/values.yaml
> Rdm 7887 anno url

- charts/ccd-api-gateway-web/Chart.yaml
- charts/ccd-api-gateway-web/requirements.yaml
> RDM-7867-Update-base-chart

- app/user/auth-checker-user-only-filter.js
- app/user/user-request-authorizer.js
- app/user/user-resolver.js
- test/user/auth-checker-user-only-filter.spec.js
- test/user/user-request-authorizer.spec.js
https://tools.hmcts.net/jira/browse/RDM-7804
Migrate CCD api gateway to OIDC
```
[ ] Yes
[ x] No
```
> RDM-7804 - CCD api gateway to OIDC

- infrastructure/perftest.tfvars
> Update IDAM URL

- Jenkinsfile_CNP
> AKS live migration

- infrastructure/perftest.tfvars
Reverts hmcts/ccd-api-gateway#309
> Revert "Update IDAM URL"

- Jenkinsfile_CNP
> Rm-installcharts()

- .github/renovate.json
- charts/ccd-api-gateway-web/Chart.yaml
- charts/ccd-api-gateway-web/requirements.yaml
> Rdm 8784 helm renovate

- ccd-yarn-audit-known-issues
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-9006
updated lodash version.
```
[ ] Yes
[X] No
```
> RDM-9006 - Periodic Confirmation/Assurance of Continued Integrity on Preview Develop-to-Develop

- charts/ccd-api-gateway-web/requirements.yaml
- charts/ccd-api-gateway-web/values.preview.template.yaml
- infrastructure/main.tf
- package.json
- yarn-audit-known-issues
- yarn.lock
> Release cut 19.1

- Jenkinsfile_CNP
- app.js
- package.json
- yarn-audit-known-issues
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-7783
Add X-Content-Type-Options: nosniff header
```
[ ] Yes
[x] No
```
> RDM-7783 - Add nosniff

- charts/ccd-api-gateway-web/Chart.yaml
- charts/ccd-api-gateway-web/values.yaml
https://tools.hmcts.net/jira/browse/RDM-10469
adjust autoscaling
```
[ ] Yes
[X] No
```
> adjust autoscaling

- charts/ccd-api-gateway-web/Chart.yaml
https://tools.hmcts.net/jira/browse/RDM-12175
Upgrade Base Chart Versions
```
[ ] Yes
[X] No
```
> RDM-12175 Upgrade Base Chart Versions

- config/default.yaml
> Update to new Postcode OS URL

- test/address/address-lookup.spec.js
> Fix address lookup unit tests

- app/oauth2/access-token-request.js
- test/oauth2/access-token-request.spec.js
Add check if redirect uri begins with undefined
```
[ ] Yes
[x] No
```
> CCD-285 Return bad request exception redirect uri

- package.json
Exclude app/oauth2/access-token-request from Sonar
```
[ ] Yes
[x] No
```
> Exclude app/oauth2/access-token-request from Sonar

- charts/ccd-api-gateway-web/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```
> update helm chart version

- test/java/build.gradle
https://tools.hmcts.net/jira/browse/CCD-3802
Update to fortify-client version
```
[ ] Yes
[ x] No
```
> CCD-3802 Update to fortify-client version

- app/address/address-lookup.js
- charts/ccd-api-gateway-web/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-3422
Fix Weak Cryptography issue in SonarCloud security hotspot
```
[ ] Yes
[ ] No
```
> Ccd 3422 math random hotspot

- .github/workflows/scheduled-dummy-commit.yml
https://tools.hmcts.net/jira/browse/CCD-3916
Update Github actions in workflow files to resolve deprecation warnings
```
[ ] Yes
[ x] No
```
> CCD-3916 Update Github actions in workflow -

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/CCD-4339
Update package versions
```
[ ] Yes
[X] No
```
> CCD-4339: Update package versions

- app/address/address-lookup.js
- app/oauth2/access-token-request.js
- app/security/cors.js
- test/cache/cache-service.spec.js
- test/user/auth-checker-user-only-filter.spec.js
- test/user/cached-user-resolver.spec.js
Ccd 1725 fix sonar cloud issues 
2 Changes
1. Completed replacing deprecated code using WHATWGAPI in access-token-request.js
2. Removed commented out code in address-lookup.js
> Ccd 1725 fix sonar cloud issues

- app/app-insights/app-insights.js
> CCD-4758 Update app-insights.js Reduce app insights health sample rate to 1%

- .github/workflows/auto-suppress-CVEs.yml
https://tools.hmcts.net/jira/browse/CCD-5467
Updating the CVE auto suppression command for nodejs repos
> Updating CVE auto supression command

- .github/workflows/auto-suppress-CVEs.yml
https://tools.hmcts.net/jira/browse/CCD-6631
CCD-6631 :: Fixed auto-suppress-CVEs.yml
```
[ ] Yes
[X] No
```
> CCD-6631 :: Fixed auto-suppress-CVEs.yml
