- app/oauth2/oauth2-route.js
Set `httpOnly` option to true, to ensure the cookie is not sent via client JavaScript, thus mitigating XSS attacks.
> RDM-1519: Securing of accessToken cookie

- app/user/auth-checker-user-only-filter.js
- test/user/auth-checker-user-only-filter.spec.js
https://tools.hmcts.net/jira/browse/RDM-1961
Add `user-id` and `user-roles` headers as part of proxying to support DM backend
> RDM-1961 Make compatible for DM backend

- infrastructure/main.tf
N/A
Booleans as string are causing an error for `is_frontend` as it's trying to convert the value to integer.
Removed the double quotes to make them integers.
```
[ ] Yes
[x] No
```
> Fix boolean as string error

- infrastructure/aat.tfvars
https://tools.hmcts.net/jira/browse/RDM-2187
To implement the shutter page, an external hostname must be registered for every frontend.
```
[ ] Yes
[x] No
```
> RDM-2187: Preparation for shutter page

- README.md
- app/oauth2/logout-route.js
- config/custom-environment-variables.yaml
- config/default.yaml
- infrastructure/main.tf
- test/oauth2/logout-route.spec.js
https://tools.hmcts.net/jira/browse/RDM-2185
The logout route on the gateway used to redirect the user to the IDAM logout page, this is now changed to call IDAM API directly to delete (revoke) the user's access token and return response to clear the access token cookie. Please also review the changes made to yaml and tf file (so it doesn't break higher environments). 
```
[ ] Yes
[x] No
```
> RDM-2185 - Redirect back to login page on logout

- app/oauth2/logout-route.js
- test/oauth2/logout-route.spec.js
https://tools.hmcts.net/jira/browse/RDM-2185
Fixed SIDAM logout API call from gateway by passing authorisation header. Works on IDAM too.
```
[ ] Yes
[x] No
```
> RDM-2185 - Redirect back to login page on logout - SIDAM api call fix

- infrastructure/main.tf
- infrastructure/preview.tfvars
Configure API Gateway to access services in AAT when deployed to a `preview` environment, and ones in SAAT when deployed to an `spreview` environment.
None.
Configure API Gateway to access services in AAT when deployed to a `preview` environment, and ones in SAAT when deployed to an `spreview` environment. Also includes a correction for S2S authentication URL when in a `preview` environment, and amendment of `CORS_ORIGIN_WHITELIST`.
```
[ ] Yes
[x] No
```
> Correct configuration for accessing external services

- config/default.yaml
setting s2s url to localhost for local development. At the moment it is configured to point to saat s2s, which creates problems when working locally with dockerised s2s service
```
[ ] Yes
[x ] No
```
> setting s2s url to localhost for local development

- app.js
- app/address/address-lookup.js
- app/oauth2/access-token-request.js
- app/service/service-filter.js
- app/user/auth-checker-user-only-filter.js
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-2529
Replace `morgan` (access login) and `console` (errors/warnings) by logger provided by `@hmcts/nodejs-logging`
```
[ ] Yes
[x] No
```
> RDM-2529: Use @hmcts/nodejs-logging

- Dockerfile
- package.json
Rationale:
- WebApps default available is 8.9.4 but 8.11.1 is available, so keep up
with what is available on Azure
- Docker based images are always the latest on the 8.x branch, with
nothing earlier.
https://tools.hmcts.net/jira/browse/RDM-3073
```
[ ] Yes
[ ] No
```
> Lock nodejs to version 8.x

- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-3684
Palo Alto only works over HTTP, https must be disabled between AppGW and
AppService
```
[ ] Yes
[x] No
```
> RDM-3684: Disable https_only

- .dockerignore
- Dockerfile
- acb.tpl.yaml
https://tools.hmcts.net/jira/browse/CNP-1131
This PR leverages on layers re-use to reduce the the docker image build time in CI:
the image build time changes from 1:30 min to 45 seconds for this project, ~half the time, if the npm dependencies do not change.
It also introduces [base nodeJS images](https://github.com/hmcts/cnp-node-base) as well as the `hmcts` user, added for security compliance.
**Does this PR introduce a breaking change?**
> Use ACR cache optimisation in pipeline

- yarn.lock
https://nodesecurity.io/advisories/780
Needed to update nice to bring in just-extend update.
```
[ ] Yes
[ ] No
```
> Bump just-extend from 3.0.0 to 4.0.2

- charts/ccd-api-gateway-web/Chart.yaml
Bumping version to publish chart after removing releasenameoverride
https://tools.hmcts.net/jira/browse/RPE-1005
Bumping version to publish chart after removing releasenameoverride
```
[ ] Yes
[x] No
```
> Bumping version to publish chart

- README.md
- web.config
https://tools.hmcts.net/jira/browse/RDM-4572
IIS web server by default allows max request content length to be 30000000 bytes (28.6 MB). 
https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/requestlimits/
This PR is to override the default value for the request filter.
```
[ ] Yes
[x] No
```
> RDM-4572 - Configure max request content length

- charts/ccd-api-gateway-web/Chart.yaml
Current published chart is broken on AAT AKS cluster .
```
[ ] Yes
[x] No
```
> Bumping chart version to publish

- charts/ccd-api-gateway-web/Chart.yaml
- charts/ccd-api-gateway-web/requirements.yaml
- charts/ccd-api-gateway-web/values.aat.template.yaml
- charts/ccd-api-gateway-web/values.preview.template.yaml
- charts/ccd-api-gateway-web/values.yaml
https://tools.hmcts.net/jira/browse/RSE-130
chart-ccd has been fixed for 3.x, since it's changing from an uber chart to parent-sub chart the microservice chart also needs a fix
We need the configurable ingress class change introduced in https://github.com/hmcts/chart-nodejs/releases/tag/v1.8.0
I've bumped the base chart and also did the updates that will be needed to deploy this to environments other than demo and preview
requires https://github.com/hmcts/ccd-shared-infrastructure/pull/42
```
[ ] Yes
[ ] No
```
> Upgrade base chart for hmcts demo

- charts/ccd-api-gateway-web/Chart.yaml
- charts/ccd-api-gateway-web/values.yaml
https://tools.hmcts.net/jira/browse/RDM-8692
The UV threadpool is used by Node to allow synchronous tasks to be performed asynchronously and not block the main node thread.
Tasks performed by this threadpool include, but are not limited to, DNS resolution - see https://nodejs.org/api/cli.html#cli_uv_threadpool_size_size
This threadpool can become a bottleneck if eg. DNS requests are slow or timeout, leading to requests queueing as they wait for an available worker thread.
Increasing the size of this threadpool is desirable for the traffic profile of api gateway, which typically handles a large number of concurrent IO bound requests.
```
[ ] Yes
[x] No
```
> RDM-8692: Increase UV_THREADPOOL_SIZE to 64

- config/default.yaml
- config/test.yaml
- yarn-audit-known-issues
yarn tests fails w/o postcode-info-address-lookup-token if APPINSIGHTS_INSTRUMENTATIONKEY is not mapped the app wont start.
```
[ ] Yes
[x] No
```
> Remove default secrets

- package.json
- yarn.lock
CCD-2293 (https://tools.hmcts.net/jira/browse/CCD-2293)
- Updated package.json.  Changed version of hmcts/properties-volume dependency to ^0.0.13.
- Regenerated yarn.lock file.
```
[ ] Yes
[x] No
```
> CCD-2293: Update hmcts/properties-volume dependency version

- package.json
- sonar-project.properties
CCD-3625 (https://tools.hmcts.net/jira/browse/CCD-3625)
Created new sonar-project.properties file and populated it with sonar properties from sonar-scan entry in package.json.  Removed sonar properties from sonar-scan entry in package.json so that they are only in one place.
This change is needed following an update to the common Jenkins pipeline code to change the sonar scanning mechanism (see https://github.com/hmcts/cnp-jenkins-library/pull/892).
```
[ ] Yes
[x] No
```
> CCD-3625: Added sonar-project.properties file

- app/app-insights/app-insights.js
Nearly 50% of HMCTS's entire Application insights log ingestion appear to be because of activity service
See also https://github.com/hmcts/ccd-case-activity-api/pull/395 for reducing it in the activity service itself
I've tested this locally with an app insights I setup just for this and it's working.
I also logged out the envelope with different URLs:
```
$ curl -H 'Authorization: Bearer 123' localhost:3453/activity/cases/1234/activity
sampleRate: 1
```
```
$ curl -H 'Authorization: Bearer 123' localhost:3453/data/internal/cases/1234
sampleRate: 100
```
> Sample activity service to reduce costs

- app/app-insights/app-insights.js
@banderous noticed that this was happening for dependencies as well. When I tested last time I didn't actually run something on that port, this time I did and could see the data.
This has been tested locally:
```
Envelope {
ver: 1,
sampleRate: 1,
tags: {
'ai.application.ver': '1.4.0',
'ai.device.id': '',
'ai.cloud.roleInstance': '***',
'ai.device.osVersion': 'Darwin 22.5.0',
'ai.cloud.role': 'ccd-api-gateway',
'ai.device.osArchitecture': 'x64',
'ai.device.osPlatform': 'darwin',
'ai.internal.sdkVersion': 'node:2.4.2',
'ai.operation.id': 'bb3f21f9932e4c3da1f89e243bb2196a',
'ai.operation.name': 'GET /activity/cases/1659733869407088/activity',
'ai.operation.parentId': '|bb3f21f9932e4c3da1f89e243bb2196a.7bf902cba76045fa.'
},
data: Data {
baseType: 'RemoteDependencyData',
baseData: …
```
> Sample remote dependency data as well for activity service

- package.json
- test/address/address-lookup.spec.js
- yarn.lock
https://tools.hmcts.net/jira/browse/CCD-5233
Fix CVE-2022-37614-mockery vulnerability dependency.
Reference to 'mockery' can safely be removed from ccd-api-gateway. &nbsp; Only used in unit tests to configure warnOnReplace , warnOnUnregistered and useCleanCache.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> CCD-5233: Fix CVE-2022-37614-mockery vulnerability dependency
